version: '3.8'

services:
  web:
    build: ./
    command: sh -c "python model.py && python main.py"
    image: kotarsis/web:latest
    ports:
      - 8005:8005
    environment:
      - DATABASE_POSTGRES=db
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=softvision

volumes:
  postgres_data: